### ISSUE TITLE
ViewportScroller is not working on angular v15

### ISSUE THREAD

**Issue by IsaacS09** [anirbmuk/angular-scroll-to-top#1]
Hi, I tried to implement scroll to top to my own project but my angular app is not working with ViewportScroller from @angular/common can you help me?

These are my dependencies: 

  "dependencies": {
    "@angular/animations": "^15.2.9",
    "@angular/cdk": "^15.2.9",
    "@angular/common": "^15.2.9",
    "@angular/compiler": "^15.2.9",
    "@angular/core": "^15.2.9",
    "@angular/fire": "^7.0.4",
    "@angular/forms": "^15.2.9",
    "@angular/material": "^15.2.9",
    "@angular/platform-browser": "^15.2.9",
    "@angular/platform-browser-dynamic": "^15.2.9",
    "@angular/router": "^15.2.9",
    "@angular/service-worker": "^15.2.9",
    "@sweetalert2/ngx-sweetalert2": "^12.1.0",
    "bootstrap": "^5.3.0",
    "firebase": "^9.21.0",
    "rxjs": "^7.8.1",
    "sweetalert2": "^11.4.8",
    "tslib": "^2.6.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.8",
    "@angular/cli": "^15.2.8",
    "@angular/compiler-cli": "^15.2.8",
    "@angular-devkit/architect": "0.1502.7",
    "typescript": "~4.8.0"
  }

**Comment by anirbmuk** [comment]
@IsaacS09 not working is not enough to describe the issue. Do you see any error? What happens when you just use `ViewportScroller` in a simple **click** listener on a button?

**Comment by IsaacS09** [comment]
Ok, I'll describe

- Don't works if I just use ViewportSCroller
- When I click the button don't do anything and console doesn't show errors
- When I use (viewport it's private readonly viewport = inject(ViewportScroller): 
-    this.viewport.scrollToPosition -> don't  do anything
-    this.viewport.getScrollPosition -> I got 0, 0 for x and y
-    this.viewport.scrollToAnchor -> don't scroll to html tags with custom id


I tried to use this in my routing module 
`
const routerOptions: ExtraOptions = {
  anchorScrolling: 'enabled',
  scrollPositionRestoration: 'enabled'
};
... 
imports: [CommonModule, RouterModule.forRoot(routes, routerOptions)],`

but doesn't works 

That's my problem @anirbmuk Thanks in advice

**Comment by anirbmuk** [comment]
@IsaacS09 I created a stackblitz project with exactly your component versions. I don't see a problem here => [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-clc2kc). It is difficult to know why it isn't working for you without viewing your code.
